import argparse
import json
import os
import re
import subprocess
import threading
import time
from datetime import datetime, timezone
from typing import Any, Dict, List

DEFAULT_USER = "openclaw"
DEFAULT_OUTPUT_ROOT = "./data"
DEFAULT_PROXY_NAMESPACE = "openclaw"
DEFAULT_OLLAMA_PROXY_DEPLOYMENT = os.getenv("OPENCLAW_OLLAMA_PROXY_DEPLOYMENT", "ollama-proxy")
DEFAULT_APIKEY_PROXY_DEPLOYMENT = os.getenv("OPENCLAW_APIKEY_PROXY_DEPLOYMENT", "dashscope-proxy")
DEFAULT_PROXY_CONTAINER = ""
DEFAULT_OLLAMA_PROXY_LOG_PATH = os.getenv(
    "OPENCLAW_OLLAMA_PROXY_LOG_PATH",
    "/var/log/ollama-proxy/openclaw_proxy_raw.jsonl",
)
DEFAULT_APIKEY_PROXY_LOG_PATH = os.getenv(
    "OPENCLAW_APIKEY_PROXY_LOG_PATH",
    "/var/log/dashscope-proxy/openclaw_proxy_raw.jsonl",
)


def _parse_iso_datetime(value: Any):
    if not isinstance(value, str):
        return None
    text = value.strip()
    if not text:
        return None
    # Robustly parse second-level datetime first, ignoring fractional/timezone tail.
    # Examples supported:
    # - 2026-03-23T19:46:34.500Z
    # - 2026-03-23T19:46:34Z
    # - 2026-03-23 19:46:34+00:00
    m = re.match(r"^(\d{4}-\d{2}-\d{2})[T ](\d{2}:\d{2}:\d{2})", text)
    if m:
        try:
            dt = datetime.strptime(f"{m.group(1)} {m.group(2)}", "%Y-%m-%d %H:%M:%S")
            return dt.replace(tzinfo=timezone.utc)
        except Exception:
            pass

    # Fallback: accept common UTC form like "2026-03-23T18:09:34.816Z".
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(text)
    except Exception:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def _to_iso_seconds(dt):
    if dt is None:
        return None
    return dt.replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _duration_seconds(start_dt, end_dt):
    if start_dt is None or end_dt is None:
        return None
    return int(round((end_dt - start_dt).total_seconds()))


def _to_single_line(value: Any) -> str:
    if not isinstance(value, str):
        return ""
    return " ".join(value.replace("\r", " ").replace("\n", " ").split())


def _extract_message_content(value: Any) -> str:
    """
    Normalize OpenAI/Ollama message content into a single-line string.
    Supports:
    - plain string
    - content parts array, e.g. [{"type":"text","text":"..."}]
    - dict wrappers containing text/content
    """
    if isinstance(value, str):
        return _to_single_line(value)

    if isinstance(value, list):
        parts: List[str] = []
        for item in value:
            text = _extract_message_content(item)
            if text:
                parts.append(text)
        return " ".join(parts).strip()

    if isinstance(value, dict):
        item_type = value.get("type")
        if item_type == "text":
            text = value.get("text")
            return _to_single_line(text) if isinstance(text, str) else ""
        if isinstance(value.get("text"), str):
            return _to_single_line(value.get("text"))
        if isinstance(value.get("content"), str):
            return _to_single_line(value.get("content"))
        if isinstance(value.get("content"), list):
            return _extract_message_content(value.get("content"))
        return ""

    return ""


def _write_json(path: str, data: Any):
    parent = os.path.dirname(path)
    if parent and not os.path.exists(parent):
        os.makedirs(parent, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fw:
        json.dump(data, fw, ensure_ascii=False, indent=2)


def _pick_header_value(record: Dict[str, Any], header_name: str):
    if not isinstance(record, dict) or not isinstance(header_name, str) or not header_name:
        return None

    target = header_name.lower()
    # Prefer request headers first: x-request-id in response can be re-generated by upstream.
    for headers_key in ("request_headers", "response_headers"):
        headers = record.get(headers_key)
        if not isinstance(headers, dict):
            continue
        for k, v in headers.items():
            if isinstance(k, str) and k.lower() == target:
                return v
    return None


def _extract_response_message(response_body: Dict[str, Any]) -> Any:
    if not isinstance(response_body, dict):
        return {}

    # Ollama style
    message = response_body.get("message")
    if isinstance(message, dict):
        return message

    # OpenAI style
    choices = response_body.get("choices")
    if isinstance(choices, list) and choices:
        first = choices[0] if isinstance(choices[0], dict) else {}
        msg = first.get("message")
        if isinstance(msg, dict):
            return msg
        # Streaming delta fallback
        delta = first.get("delta")
        if isinstance(delta, dict):
            return {
                "role": delta.get("role") or "assistant",
                "content": delta.get("content"),
                "tool_calls": delta.get("tool_calls", []),
            }

    return {}


def _extract_token_usage(response_body: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(response_body, dict):
        return {"token_input": None, "token_output": None}

    usage = response_body.get("usage")
    if isinstance(usage, dict):
        return {
            "token_input": usage.get("prompt_tokens"),
            "token_output": usage.get("completion_tokens"),
        }

    return {
        "token_input": response_body.get("prompt_eval_count"),
        "token_output": response_body.get("eval_count"),
    }


def _compact_message(msg: Any) -> Dict[str, Any]:
    if not isinstance(msg, dict):
        return {"role": "", "content": "", "tool_calls": []}
    role = msg.get("role")
    if not isinstance(role, str):
        role = ""
    tool_calls = msg.get("tool_calls")
    if not isinstance(tool_calls, list):
        tool_calls = []
    return {
        "role": role,
        "content": _extract_message_content(msg.get("content")),
        "tool_calls": tool_calls,
    }


def build_openclaw_ollama_tidy(ollama_raw_path: str, tidy_dir: str, output_filename: str = "openclaw_ollama_tidy.json") -> str:
    with open(ollama_raw_path, "r", encoding="utf-8") as fr:
        raw_obj = json.load(fr)

    records = raw_obj.get("records", [])
    tidy_records = []
    for record in records:
        if not isinstance(record, dict):
            continue

        start_dt = _parse_iso_datetime(record.get("timestamp"))
        response_body = record.get("response_body")
        if not isinstance(response_body, dict):
            response_body = {}
        # Prefer proxy-captured response timestamp when available (most accurate end time).
        end_dt = _parse_iso_datetime(record.get("response_timestamp"))
        if end_dt is None:
            end_dt = _parse_iso_datetime(response_body.get("created_at"))
        if end_dt is None:
            created_unix = response_body.get("created")
            if isinstance(created_unix, (int, float)) and created_unix > 0:
                try:
                    end_dt = datetime.fromtimestamp(float(created_unix), tz=timezone.utc)
                except Exception:
                    end_dt = None
        if end_dt is None:
            response_headers = record.get("response_headers")
            if isinstance(response_headers, dict):
                date_header = response_headers.get("date")
                if isinstance(date_header, str) and date_header:
                    try:
                        # Example: "Mon, 23 Mar 2026 18:10:44 GMT"
                        end_dt = datetime.strptime(date_header, "%a, %d %b %Y %H:%M:%S GMT").replace(
                            tzinfo=timezone.utc
                        )
                    except Exception:
                        end_dt = None

        request_body = record.get("request_body")
        if not isinstance(request_body, dict):
            request_body = {}
        request_messages_raw = request_body.get("messages")
        if not isinstance(request_messages_raw, list):
            request_messages_raw = []

        request_messages = [_compact_message(m) for m in request_messages_raw if isinstance(m, dict)]
        latest_message = request_messages[-1] if request_messages else None
        response_message = _compact_message(_extract_response_message(response_body))
        if not response_message.get("content"):
            response_message["content"] = _extract_message_content(record.get("response_completion_merged"))
        if not response_message.get("tool_calls"):
            merged_tool_calls = record.get("response_tool_calls_merged")
            if isinstance(merged_tool_calls, list):
                response_message["tool_calls"] = [tc for tc in merged_tool_calls if isinstance(tc, dict)]
        tokens = _extract_token_usage(response_body)

        tidy_records.append(
            {
                "timestamp": _to_iso_seconds(start_dt),
                "end_time": _to_iso_seconds(end_dt),
                "request_id": _pick_header_value(record, "x-request-id"),
                "istio_trace_id": _pick_header_value(record, "x-b3-traceid"),
                "istio_span_id": _pick_header_value(record, "x-b3-spanid"),
                "istio_parentspanid": _pick_header_value(record, "x-b3-parentspanid"),
                "model": response_body.get("model") or request_body.get("model"),
                "token_input": tokens.get("token_input"),
                "token_output": tokens.get("token_output"),
                "duration": _duration_seconds(start_dt, end_dt),
                "latest_message": latest_message,
                "request_messages": request_messages,
                "response_message": response_message,
            }
        )

    out_path = os.path.join(tidy_dir, output_filename)
    _write_json(out_path, tidy_records)
    return out_path


def _start_progress_timer(watch_seconds: int):
    """
    Print elapsed collection time every 30 seconds.
    Returns a stop function that should be called when collection ends.
    """
    if watch_seconds <= 0:
        return lambda: None

    stop_event = threading.Event()
    start_ts = time.monotonic()

    def _worker():
        tick = 30
        while not stop_event.wait(1):
            elapsed = int(time.monotonic() - start_ts)
            if elapsed >= tick:
                print(f"[timer] 已运行 {elapsed}s / {watch_seconds}s")
                tick += 30

    thread = threading.Thread(target=_worker, daemon=True)
    thread.start()

    def _stop():
        stop_event.set()
        thread.join(timeout=1)

    return _stop


class OllamaProxyRawCollector:
    """
    Collect raw jsonl logs from ollama-proxy pod file and export json.
    """

    def __init__(self, namespace: str, deployment: str, log_path: str, container: str = ""):
        self.namespace = namespace
        self.deployment = deployment
        self.log_path = log_path
        self.container = container.strip()

    def _run(self, cmd: List[str]) -> str:
        proc = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                "Failed to run kubectl command for ollama-proxy.\n"
                f"Command: {' '.join(cmd)}\n"
                f"stderr: {proc.stderr.strip()}"
            )
        return proc.stdout

    def _exec_shell(self, shell_script: str) -> str:
        cmd = [
            "kubectl",
            "-n",
            self.namespace,
            "exec",
            f"deploy/{self.deployment}",
        ]
        if self.container:
            cmd.extend(["-c", self.container])
        cmd.extend(["--", "sh", "-c", shell_script])
        return self._run(cmd)

    def mark_start_line(self) -> int:
        # 1-based line number to read from later
        out = self._exec_shell(f"if [ -f '{self.log_path}' ]; then wc -l < '{self.log_path}'; else echo 0; fi")
        try:
            current = int((out or "0").strip())
        except Exception:
            current = 0
        return current + 1

    def fetch_since_line(self, start_line: int) -> str:
        script = (
            f"if [ -f '{self.log_path}' ]; then "
            f"sed -n '{max(1, int(start_line))},$p' '{self.log_path}'; "
            "fi"
        )
        return self._exec_shell(script)

    @staticmethod
    def _dedupe_tool_calls(tool_calls: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        seen = set()
        unique_calls: List[Dict[str, Any]] = []
        for item in tool_calls:
            try:
                key = json.dumps(item, ensure_ascii=False, sort_keys=True)
            except Exception:
                key = str(item)
            if key in seen:
                continue
            seen.add(key)
            unique_calls.append(item)
        return unique_calls

    @classmethod
    def _merge_response_stream(cls, record: Dict[str, Any]) -> Dict[str, Any]:
        """
        Merge streamed Ollama ndjson chunks from `response_body_raw` back into
        `response_body.message`:
        - fill message.content (fallback to merged thinking when content is empty)
        - attach merged tool_calls when present
        - expose `response_completion_merged` for downstream analysis
        """
        if not isinstance(record, dict):
            return record

        raw_stream = record.get("response_body_raw")
        if not isinstance(raw_stream, str) or not raw_stream.strip():
            return record

        chunks: List[Dict[str, Any]] = []
        for line in raw_stream.splitlines():
            s = line.strip()
            if not s:
                continue
            try:
                item = json.loads(s)
            except Exception:
                continue
            if isinstance(item, dict):
                chunks.append(item)

        if not chunks:
            return record

        content_parts: List[str] = []
        thinking_parts: List[str] = []
        all_tool_calls: List[Dict[str, Any]] = []

        for chunk in chunks:
            msg = chunk.get("message")
            if not isinstance(msg, dict):
                continue

            content = msg.get("content")
            if isinstance(content, str) and content:
                content_parts.append(content)

            thinking = msg.get("thinking")
            if isinstance(thinking, str) and thinking:
                thinking_parts.append(thinking)

            tool_calls = msg.get("tool_calls")
            if isinstance(tool_calls, list):
                all_tool_calls.extend([tc for tc in tool_calls if isinstance(tc, dict)])

        merged_content = "".join(content_parts)
        merged_thinking = "".join(thinking_parts)
        merged_completion = merged_content if merged_content else merged_thinking
        merged_tool_calls = cls._dedupe_tool_calls(all_tool_calls)

        body = record.get("response_body")
        if not isinstance(body, dict):
            body = {}
            record["response_body"] = body

        message = body.get("message")
        if not isinstance(message, dict):
            message = {"role": "assistant", "content": ""}
            body["message"] = message

        current_content = message.get("content")
        if (not isinstance(current_content, str)) or (not current_content):
            if merged_completion:
                message["content"] = merged_completion

        if merged_tool_calls:
            existing_tool_calls = message.get("tool_calls")
            if isinstance(existing_tool_calls, list):
                merged = existing_tool_calls + merged_tool_calls
                message["tool_calls"] = cls._dedupe_tool_calls([tc for tc in merged if isinstance(tc, dict)])
            else:
                message["tool_calls"] = merged_tool_calls

        record["response_completion_merged"] = merged_completion if merged_completion else None
        return record

    @staticmethod
    def _parse_jsonl(raw_text: str) -> Dict:
        raw_lines = raw_text.splitlines()
        records = []
        invalid_lines = []
        for idx, line in enumerate(raw_lines, start=1):
            s = line.strip()
            if not s:
                continue
            try:
                record = json.loads(s)
                if isinstance(record, dict):
                    record = OllamaProxyRawCollector._merge_response_stream(record)
                records.append(record)
            except Exception:
                invalid_lines.append({"line_no": idx, "line": line})
        return {
            "raw_lines": raw_lines,
            "records": records,
            "invalid_lines": invalid_lines,
        }

    def export_raw_json(self, raw_text: str, out_dir: str, output_filename: str = "openclaw_ollama_raw.json") -> Dict:
        payload = self._parse_jsonl(raw_text)
        output = {
            "meta": {
                "proxy_namespace": self.namespace,
                "proxy_deployment": self.deployment,
                "proxy_container": self.container,
                "proxy_log_path": self.log_path,
            },
            "counts": {
                "raw_lines": int(len(payload["raw_lines"])),
                "records": int(len(payload["records"])),
                "invalid_lines": int(len(payload["invalid_lines"])),
            },
            "records": payload["records"],
            "invalid_lines": payload["invalid_lines"],
            "raw_lines": payload["raw_lines"],
        }
        raw_dir = os.path.join(out_dir, "raw")
        os.makedirs(raw_dir, exist_ok=True)
        out_path = os.path.join(raw_dir, output_filename)
        with open(out_path, "w", encoding="utf-8") as fw:
            json.dump(output, fw, ensure_ascii=False, indent=2)
        return {
            "path": out_path,
            "raw_lines": output["counts"]["raw_lines"],
            "records": output["counts"]["records"],
            "invalid_lines": output["counts"]["invalid_lines"],
        }


def _k8s_deployment_exists(namespace: str, deployment: str) -> bool:
    if not deployment:
        return False
    cmd = ["kubectl", "-n", namespace, "get", "deployment", deployment]
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
    return proc.returncode == 0


def parse_args():
    parser = argparse.ArgumentParser(
        description="Collect OpenClaw telemetry. Only one argument is required: monitoring seconds."
    )
    parser.add_argument(
        "watch_seconds",
        type=int,
        help="Monitoring duration in seconds, e.g. 180.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    monitor_mode = ""
    while monitor_mode not in ("1", "2"):
        monitor_mode = input("使用ollama监测键入1,使用apikey键入2：").strip()
        if monitor_mode not in ("1", "2"):
            print("输入无效，请输入 1 或 2。")

    if monitor_mode == "1":
        proxy_raw_filename = "openclaw_ollama_raw.json"
        proxy_tidy_filename = "openclaw_ollama_tidy.json"
        mode_name = "ollama"
        proxy_deployment = DEFAULT_OLLAMA_PROXY_DEPLOYMENT
        proxy_log_path = DEFAULT_OLLAMA_PROXY_LOG_PATH
    else:
        proxy_raw_filename = "openclaw_dashscope_proxy.json"
        proxy_tidy_filename = "openclaw_dashscope_tidy.json"
        mode_name = "apikey"
        proxy_deployment = DEFAULT_APIKEY_PROXY_DEPLOYMENT
        proxy_log_path = DEFAULT_APIKEY_PROXY_LOG_PATH
        if not _k8s_deployment_exists(DEFAULT_PROXY_NAMESPACE, proxy_deployment):
            if _k8s_deployment_exists(DEFAULT_PROXY_NAMESPACE, DEFAULT_OLLAMA_PROXY_DEPLOYMENT):
                print(
                    "[warn] 未找到 apikey 代理 deployment，已回退为 ollama-proxy。"
                    f" 可通过环境变量 OPENCLAW_APIKEY_PROXY_DEPLOYMENT 指定（当前: {proxy_deployment}）。"
                )
                proxy_deployment = DEFAULT_OLLAMA_PROXY_DEPLOYMENT
                proxy_log_path = DEFAULT_OLLAMA_PROXY_LOG_PATH
            else:
                raise RuntimeError(
                    "方式2(apikey)代理 deployment 不存在。"
                    f" 当前配置: {DEFAULT_PROXY_NAMESPACE}/{proxy_deployment}。"
                    " 请确认 deployment 名称，或设置环境变量 OPENCLAW_APIKEY_PROXY_DEPLOYMENT / "
                    "OPENCLAW_APIKEY_PROXY_LOG_PATH 后重试。"
                )

    out_dir = os.path.join(DEFAULT_OUTPUT_ROOT, str(DEFAULT_USER))
    proxy_collector = OllamaProxyRawCollector(
        namespace=DEFAULT_PROXY_NAMESPACE,
        deployment=proxy_deployment,
        container=DEFAULT_PROXY_CONTAINER,
        log_path=proxy_log_path,
    )

    print(f"Monitoring mode: {mode_name}")
    print(
        "Collecting proxy raw logs from "
        f"deploy/{proxy_deployment} in ns/{DEFAULT_PROXY_NAMESPACE}, "
        f"log_path={proxy_log_path}"
    )
    proxy_start_line = proxy_collector.mark_start_line()
    stop_timer = _start_progress_timer(args.watch_seconds)
    try:
        time.sleep(max(0, int(args.watch_seconds)))
    finally:
        stop_timer()
    proxy_raw = proxy_collector.fetch_since_line(proxy_start_line)
    proxy_result = proxy_collector.export_raw_json(proxy_raw, out_dir, output_filename=proxy_raw_filename)
    tidy_dir = os.path.join(out_dir, "tidy")
    proxy_tidy_path = build_openclaw_ollama_tidy(proxy_result["path"], tidy_dir, output_filename=proxy_tidy_filename)

    print(f"\nOpenClaw export completed: {out_dir}")
    print(f"  Proxy Raw JSON: {proxy_result['path']}")
    print(f"  Tidy Proxy JSON: {proxy_tidy_path}")
    print(
        f"  Proxy lines: {proxy_result['raw_lines']}, parsed records: {proxy_result['records']}, "
        f"invalid lines: {proxy_result['invalid_lines']}"
    )


if __name__ == "__main__":
    main()